apiVersion: v1
kind: Pod
metadata:
  name: mysqldb
  labels:
    app: mysqldb
spec:
  containers:
    - name: mysqldb
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_DATABASE
          value: fleetdb

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: mysqldb
  ports:
    - port: 3306
  type: ClusterIP
