apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    app: client
    release: "0"
spec:
  containers:
    - name: client
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
apiVersion: v1
kind: Pod
metadata:
  name: client-r0
  labels:
    app: client
    release: "0.5"
spec:
  containers:
    - name: client
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
spec:
  containers:
    - name: queue
      image: richardchesterwood/k8s-fleetman-queue:release1
