apiVersion: v1
kind: Service
metadata:
  #this service becomes a network endpoint for other services within or outside the cluster (e.g. browser)
  #it will be referred by the name below
  name: fleet-web
spec:
  #selects resources affected by this service
  selector:
    app: client
    #release: "0.5"
  ports:
    #name is a helpful description for the traffic expected
    - name: http
      #accept traffic on the port below
      port: 80
      #forward accepted traffic to the port below
      targetPort: 80 #default to port above unless otherwise specified
      #when using type NodePort, nodePort specifies the port for the node. Must be between 30,000 - 30,767
      nodePort: 30080
  #type clusterIP is only accessible from within the cluster, and inaccessible to external traffic
  #type NodePort exposes the service through the node to outside traffic
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  #this service becomes a network endpoint for other services within or outside the cluster (e.g. browser)
  #it will be referred by the name below
  name: fleet-queue
spec:
  #selects pods that will be under this service
  selector:
    app: queue
  ports:
    #name is a helpful description for the traffic expected
    - name: http
      #accept traffic on the port below
      port: 8161
      #forward accepted traffic to the port below
      #targetPort: 80 #default to port above unless otherwise specified
      #when using type NodePort, nodePort specifies the port for the node. Must be between 30,000 - 30,767
      nodePort: 30010
  #type clusterIP is only accessible from within the cluster, and inaccessible to external traffic
  #type NodePort exposes the service through the node to outside traffic
  type: NodePort
