apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: default
type: Opaque
data:
  # Example:
  # password: {{ .Values.password | b64enc }}
  accessKey: MTIzNDU2Nzg5MAo=
  secretKey: U0VDUkVUMTIzNAo=
