apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue-mq
  type: ClusterIP
  ports:
    - name: admin
      port: 8161
    - name: endpoint
      port: 61616

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-track
  type: ClusterIP
  ports:
    - name: http
      port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gate
  type: ClusterIP
  ports:
    - name: http
      port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - name: http
      port: 80
