#Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  storageClassName: cloud-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
#Binding - enough storage space, correct access mode, matching storageClass

---
#Implementation - GCP
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
